#!/bin/sh

[ -z $GTK3DIALOG ] && GTK3DIALOG=gtk3dialog

MAIN_DIALOG='
<window>
	<vbox>
		<hbox>
			<text>
				<label>whoami:</label>
			</text>
			<entry>
				<input>whoami</input>
				<variable>ENTRY</variable>
			</entry>
		</hbox>
		<hbox>
			<button ok></button>
			<button cancel></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTK3DIALOG --program=MAIN_DIALOG ;;
esac
