#!/bin/sh

[ -z $GTK3DIALOG ] && GTK3DIALOG=gtk3dialog

if [ -z "WAYLAND_DISPLAY" ]; then
	echo '<window>
	       <vbox>
	         <text><label>ERROR: You are not running wayland</label></text>
	       <hbox>
	         <button ok></button>
	       </hbox>
	       </vbox>
	     </window>' | $GTK3DIALOG -s
	     exit
fi

export PID=$$
export SPID

fnc_msg() {
	echo '<window layer="top" edge="top" dist="200"  width-request="200">
	<vbox name="splash">
		<hbox name="splash">
		<pixmap name="splash"><width>42</width><input file icon="gtk-info"></input></pixmap>
		<text name="splash">
			<label>The window below may be covered. Just wait.</label>
		</text>
		</hbox>
		<hbox name="splash">
			<button ok></button>
		</hbox>
	</vbox>
</window>' | $GTK3DIALOG -s --styles=./window.css  & SPID=$!
}

for i in background bottom top overlay
do
	o=" $i"
	case $i in
		background)fnc_msg;T='All windows can cover this.'; TIMER='<timer interval="4" visible="false"><action>kill '$SPID'</action><action>exit:BYE</action></timer>';;
		bottom)T='Most windows can cover this.'; TIMER='<timer interval="6" visible="false"><action>exit:BYE</action></timer>';;
		top)T='Only overlay windows can cover this.'; TIMER='';;
		overlay)T='No windows can cover this.';o="n $i"; TIMER='';;
	esac
	

MAIN_DIALOG='
<window layer="'$i'" width-request="320">
	<vbox>
		<frame Layers>
			<text use-markup="true" tooltip-text="Drag a window over this one to test">
				<label>"<big><big>This is a'$o' window.</big></big>"</label>
			</text>
			<text>
				<label>'$T'</label>
			</text>
			'$TIMER'
		</frame>
		<hbox>
			<button ok></button>
			<button>
				<label>Cancel</label>
				<input file icon="gtk-cancel"></input>
				<action>kill '$PID'</action>
				<action>exit:CANCEL</action>
			</button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTK3DIALOG --program=MAIN_DIALOG --styles=./window.css ;;
esac
done
