#!/bin/sh

[ -z $GTK3DIALOG ] && GTK3DIALOG=gtk3dialog

MAIN_DIALOG='
<window>
	<vbox>
		<edit>
			<variable>EDITOR</variable>
			<height>150</height>
			<width>350</width>
			<default>
"This is the default text of the editor."
			</default>
		</edit>
		<hbox>
			<button cancel></button>
			<button ok></button>
		</hbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTK3DIALOG --program=MAIN_DIALOG ;;
esac
